---
title: "The Overwhelming Expectations That Come With The Title 'Data Scientist'"
author: "Audrey Bertin"
date: "3/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In a few months I'll be graduating and heading off into the real world as a data scientist. Before I came to college, I used to think that this title just meant that I'd be a cool data nerd who makes fun visualizations and answers interesting questions, but my studies into data ethics have made it clear that in reality, data science is so much more than that. This is true in terms of both the fact that data scientists have a lot of ethical responsibility to consider, but also in terms of the job description itself.

As talked about in Ch 5 of *Data Feminism*, society has this belief that all data scientists should be unicorns---people who can do it all: design and conduct experiments, collect and engineer data, analyze it, visualize it, and communicate about it effectively. I see this kind of thing in job postings all the time: employers want you to be able to code in 4 languages and use 7 different pieces of software, and have experience in this, that, and the other. As someone who is about to go out into the real world and hold a job with the title of "Data Scientist" in it, this kind of belief feels incredibly overwhelming. The societal expectations placed on data scientists by the world feel ridiculous at times. Realistically, how many people can *really* be skilled at all of those different things? It's next to impossible.

The most frustrating thing is that these expectations seem to often be placed on data scientists by those who aren't really familiar with what data science is really like. Data scientists aren't people who can do it all. They aren't unicorns. As *Data Feminism* describes, they're just one chain in the list of many people who help make an analysis possible, from those who conduct interviews at the local level, to those who choose which data to collect, to those who format it for analysis, and so on. But nobody realizes this---they see data scientists as the faces of this analysis process, since they typically are responsible for the visualization aspect---and thus hold them responsible for the whole thing.

This undermines both those who are incredibly important to the process, but unseen, *and* the data scientists who have impossible expectations placed on them.

Although I'm confident in my skills, I know there is simply no way I can be what society wants me to be and and do it all. There is not enough time in the day to learn and execute all those steps, and a work-life balance is incredibly important to me. But the more that society idealizes this image of the unicorn data scientist, the more likely it is that I'll be expected to be this type of person---especially if I work for a company or organization who is new to data science and does not understand the full complexity and challenge that data analysis can bring. 

Dispelling the unicorn notion would be incredibly helpful to mitigating these issues, but the more I read *Data Feminism*, the more it becomes clear how challenging of a task that really is! Dismantling "unicornism" would require changing the public perception of data science to make clear just how many people are truly involved---to make visible the invisible labor that plays such an important role in this industry. But this task feels almost impossible. With poor documentation, how can you do any more than just analyze the data for what you think it is? How can you uncover who made it and the conditions in which it was created? I don't even know how to start answering those questions, and that scares me a bit. 

Sometimes it feels like we've dug ourselves into a hole by propping data science up on a pedestal, setting high expectations, and focusing purely on visualization over the other steps of the analysis process. Will we ever get out of this hole? I don't know, and I really hope this hole---and the "unicorn" concept---do not come back to haunt me.